### ISSUE TITLE
Node JS http-server is not installed, would you like to install it?

### ISSUE THREAD

**Issue by DeltaOn3X** [FrostySo/Ps4-Pkg-Sender#18] opened 2021-12-18 08:22 UTC
Hello,

im trying to use the latest version of pkg sender (1.06 NodeJSFix). As soon as I start the program, I get the message that http-server is not installed. Even when i type npm install http-server in cmd it still shows the message. 

pk sender asks me to install http server and whenever i click on yes it fails to install. 

When i get the message and press no, pkg sender opens normaly but it fails often to send a pkg

**Comment by DeltaOn3X** [comment] 2021-12-18 09:03
When i connect my ps4 with my laptop over a lan cable, i always get http 500 error or adress already in use

**Comment by TheRadziu** [comment] 2021-12-18 11:44
been using v1.04 since 6.72, but recently got the same issue with npm http-server detection after certain windows 11 update. 
Same happens on 1.06 NodeJSFix. Although in my case I can accept install or deny it, and Pkg sender will still work just fine, its just detection issue.

**Comment by FrostySo** [comment] 2021-12-18 17:11
Are you guys both using windows 11? This would be hard to debug due to not having windows 11 myself. 

Could you guys both do me a favor and go to CMD and type "http-server -v" and "npm" and paste me the output of them both?

**Comment by FrostySo** [comment] 2021-12-18 17:22
> When i connect my ps4 with my laptop over a lan cable, i always get http 500 error or adress already in use

These kind of problems are hard to know the cause because of your network setup. "Address already in use" means that a program is using the port number already. I thought I added detection to use another port, but I don't quite remember if I'm honest. 

If you could open up powershell and paste this in 

```Get-Process -Id (Get-NetTCPConnection -LocalPort 8080).OwningProcess```

And it will tell you the process that is using the port number up. If it returns a red screen of errors then it means no process is using that port. 

As for the HTTP 500, this is common for not having the correct setup. Did you follow the steps on one of Modded Warfare's videos?  https://youtu.be/v04zI5SD07k You can use this video here and follow the steps. Just to ensure if you're doing it correctly. 

But if you guys are both using windows 11 then my support that I can offer to you is minimal. I'm not sure what kind of changes they've made in the OS. I could try upping the .NET Framework version to a higher version, to see if that resolves some functionality issues you may be facing?

**Comment by TheRadziu** [comment] 2021-12-18 17:51
> Are you guys both using windows 11? This would be hard to debug due to not having windows 11 myself.
> 
> Could you guys both do me a favor and go to CMD and type "http-server -v" and "npm" and paste me the output of them both?

I do, both commands returns as expected
```C:\Users\Radziu>http-server -v
v14.0.0

C:\Users\Radziu>npm

Usage: npm <command>```

**Comment by FrostySo** [comment] 2021-12-18 17:59
> > Are you guys both using windows 11? This would be hard to debug due to not having windows 11 myself.
> > Could you guys both do me a favor and go to CMD and type "http-server -v" and "npm" and paste me the output of them both?
> 
> I do, both commands returns as expected
> 
> ```
> C:\Users\Radziu>http-server -v
> v14.0.0
> 
> C:\Users\Radziu>npm
> 
> Usage: npm <command>
> blahblah and so on
> ```

Must be a change in the API for how their CMD works in windows 11. I'm not sure how I can help you because it isn't easy to test things without having the actual OS at hand to play around with. I'll try use a VM for Win11 and see if I can replicate the same issue you're having.

**Comment by Magzen48** [comment] 2021-12-18 19:52
> > > Are you guys both using windows 11? This would be hard to debug due to not having windows 11 myself.
> > > Could you guys both do me a favor and go to CMD and type "http-server -v" and "npm" and paste me the output of them both?
> > 
> > 
> > I do, both commands returns as expected
> > ```
> > C:\Users\Radziu>http-server -v
> > v14.0.0
> > 
> > C:\Users\Radziu>npm
> > 
> > Usage: npm <command>
> > blahblah and so on
> > ```
> 
> Must be a change in the API for how their CMD works in windows 11. I'm not sure how I can help you because it isn't easy to test things without having the actual OS at hand to play around with. I'll try use a VM for Win11 and see if I can replicate the same issue you're having.

Hi iam using Windows 10 21H2, i got the same issue with Node JS, Failed to Install... Please run "npm install http-server

Have runned the command several times but didnt help solve the issue, also tried installing older versions of Node JS from 2020 but still the same popup.

**Comment by Magzen48** [comment] 2021-12-18 20:04
It was solved for me, when iam prompted with the question if i want to install http-server i just click no and then i can use PS4 PKg Sender as normal, hope it helps.

**Comment by FrostySo** [comment] 2021-12-18 20:05
Okay, I just realized that Http-Server is now on v14 while I check for `v0.` I will change it to support a regular expressions which should solve your guys issues. Guess when I made this I just assumed all revisions would increment in 0.XY. Guess I was wrong.

**Comment by FrostySo** [comment] 2021-12-18 20:31
Can any of you guys test this out and let me know if it works or not? 

[Ps4 Pkg Sender V1.07.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/7739916/Ps4.Pkg.Sender.V1.07.zip)

Works for me, but I'd like confirmation it works for you guys before pushing the update.

**Comment by Magzen48** [comment] 2021-12-18 20:43
> Can any of you guys test this out and let me know if it works or not?
> 
> [Ps4 Pkg Sender V1.07.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/7739916/Ps4.Pkg.Sender.V1.07.zip)
> 
> Works for me, but I'd like confirmation it works for you guys before pushing the update.

Works great for me, compared to 1.06 it doesnt ask anymore about Node JS install http server when it is already installed.

**Comment by GARBAGEPLAY** [comment] 2021-12-19 00:47
> Can any of you guys test this out and let me know if it works or not?
> 
> [Ps4 Pkg Sender V1.07.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/7739916/Ps4.Pkg.Sender.V1.07.zip)
> 
> Works for me, but I'd like confirmation it works for you guys before pushing the update.

Works fine. Thanks!

**Comment by DeltaOn3X** [comment] 2021-12-19 01:33
Sorry for the late reply, i opened the issue and was outside the whole next day.

I was testing it on a windows 11 and a windows 10 machine, both had those error message.

I can confirm that 1.07 works without a error message but i cant really send big files (7gb) files. 

It always stop at 13/14%, i tried several pkgs but that is maybe an error on my side. 

Im still giving it a few tries, maybe try it with a lan cable to get faster speeds.

(Small DLC files works like a charm)

Still great work and thank you very much for updating it so fast!

**Comment by FrostySo** [comment] 2021-12-19 02:41
It's most likely on your guys end. 

Also for the percentages, it refreshes on a countdown. If you tab out of RPI as well, it will not update the percentages as the api  doesn't seem to send updated info unless you are focused on it. 

If you could share the pkg file names, I could give it a go myself to confirm if it's the pkg file or an issue on your end. Refer to issue #3 . RPI doesn't work for some packages, I've yet to find out the cause of it. There are some pkg files that are missing metadata which rpi relies on

**Comment by DeltaOn3X** [comment] 2021-12-19 02:46
The name of the package is godofwar.pkg, i can use filezilla over lan perfectly and copy games with 1gbit over.

Over wifi i can send a big file until 13/14%, in the task manager i also see how he drops from 60-70mbits to 0 and stays there.

The big file were named UP9000-CUSA07408_00-00000000GODOFWAR-A0100-V0100

(God.of.War.v1.34.PATCH.PS4-CUSA07408.pkg too)

**Comment by FrostySo** [comment] 2021-12-19 05:26
> The name of the package is godofwar.pkg, i can use filezilla over lan perfectly and copy games with 1gbit over.
> 
> Over wifi i can send a big file until 13/14%, in the task manager i also see how he drops from 60-70mbits to 0 and stays there.
> 
> The big file were named UP9000-CUSA07408_00-00000000GODOFWAR-A0100-V0100
> 
> (God.of.War.v1.34.PATCH.PS4-CUSA07408.pkg too)
> 
> I already saw some posts where the name should have nothing special in it but godofwar.pgk should than.
> 
> The small dlcs working fine and they also named like this UP9000-CUSA07408_00-PO00010000000000-A0000-V0100.pkg.
> 
> But i guess this is just on my end because no pkg sender is working xD.
> 
> I may try other ones over wifi and look if they are stopping too.

Yea it works for me so it's on your end.

**Comment by ZedFuzz** [comment] 2021-12-19 11:31
Hi, I had the same exact problem as described by @DeltaOn3X until I found a troubleshooting video which refers the installation of [NodeJS v 14.15.3](https://nodejs.org/download/release/v14.15.3/). This solved any issue I had and I have been remotely installing games ever since (did a 26GB game yesterday).

Any newer installlations of Nodejs popped the same error of "can't install http-server".

[Link to the video](https://www.youtube.com/watch?v=J5b9ky1crX0), if interested

**Comment by DeltaOn3X** [comment] 2021-12-19 16:02
Really weird, over wifi it sometimes work, sometimes not. 
Over LAN i cant use any pkg sender even when i setup everything correctly. dont know what is wrong on my setup since you just share ur wifi connection to ur ethernet connection and plug in an ethernet cable to ur ps4 and youre good to go.

**Comment by FrostySo** [comment] 2021-12-20 03:27
> Really weird, over wifi it sometimes work, sometimes not. Over LAN i cant use any pkg sender even when i setup everything correctly. dont know what is wrong on my setup since you just share ur wifi connection to ur ethernet connection and plug in an ethernet cable to ur ps4 and youre good to go.
> 
> EDIT: Ok when i ping my ps4 while sending pkgs over wifi i can see that i get a timeout after a certain time and than the pkg sender just stops there and will not resume as it seems like. When i let pkg sender like that it will stay on whatever % it got the timeout on my ping. Is the pgk sender able to resume it even when i get a connection loss for just a second ?
> 
> EDIT2: Ok i tried it again with LAN and suddenly it didnt really saved my firewall settings so i checked again and allowed for both node and the pkg sender the connection and now i can send pkgs over lan perfectly!
> 
> Because of my timeouts i get on wifi is prob just the fault of my shit router since its one of the worst routers you can get here in germany (fuck vodafone), with a fritzbox it should work fine with wifi too.

Glad you got it fixed! Closing because resolved

**Closed by FrostySo** 2021-12-20 03:27 UTC
